server
{
	listen 8002;
	location /
	{
		root ./www/pretty/;
		post_directory ./www/pretty/posted_img/;
		allow_methods  GET POST DELETE;
		error_page 404 500 ./www/error_pages/404.html;
		autoindex on;
		client_max_body_size 3000000;
		client_max_header_size 3000000;
	}
	
	location /posted_img
	{
		root ./www/pretty/;
		autoindex on;
		allow_methods  GET;
	}
}
